---
title: "01session"
author: "Zoé Wolter & Philipp Bosch"
date: "Oct 21, 2022"
output: html_document
---

# AGENDA

- Intro: Was ist Web Scraping überhaupt?
- Einführung in das Projekt für den Workshop
- Download von HTMLs
- Extrahieren von Informationen aus den HTMLs

# Intro: Was ist Web Scraping überhaupt?
Bei Web Scraping geht es um das Sammeln von Informationen von Websites, indem man diese direkt aus dem HTML Source Code extrahiert. Warum denn aber?

- Daten über Daten
- kein Copy&Paste mehr
- Automatisierung der Datensammlung
- reproduzierbare und aktualisierbare Datensammlung

# Unser Ziel
Heute:
  - Den Aufbau von HTMLs verstehen
  - Extraktion von Informationen anhand ihrer XPaths
  - Anwenden auf cyberLAGO-Event-Homepage


# Packages laden

Zuerst (installieren und) laden wir alle Packages, die wir heute und am zweiten Workshop-Tag benötigen: 
```{r}
source(knitr::purl("packages.Rmd", quiet = TRUE))
```

# Events Homepage

## URL

Zuerst suchen wir uns die URL, von der wir uns die Daten ziehen wollen. Diese speichern wir für die weitere Bearbeitung in einem Vektor. Dafür speichern wir entweder die Base URL (Stamm-URL), von der aus man weitere URLs zusammenbauen kann oder direkt die gesamte URL:
